site_name: Rangkuman Komputasi Numerik
theme:
  name: material
nav:
    - Tentang: 'index.md'
    - "Turunan Numerik":
      - "Teori": "turunan-numerik/1. teori.md"
      - "Algoritma": "turunan-numerik/2. algoritma.md"
      - "Kode": "turunan-numerik/3. kode.md"
    - "Numerical Solution of System of Linear Algebraic Equations":
      - "Teori": "sistem-persamaan-linear/1. teori.md"
      - "Algoritma": "sistem-persamaan-linear/2. algoritma.md"
      - "Kode": "sistem-persamaan-linear/3. kode.md"
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  